### PR TITLE
Made ReadMe 0.304023402042304243903508% better

### PR DESCRIPTION
**Pull request by pgamerx**
yus

### CODE REVIEW

**Comment by ghost** [comment]
bruh

**Comment by ghost** [comment]
how did you calculate?

**Comment by StarTwi** [comment]
Imao did you even do something?

**Comment by ghost** [comment]
> Imao did you even do something?

he did kek.

**Comment by pgamerx** [comment]
> Imao did you even do something?

Yep

**Comment by pgamerx** [comment]
> how did you calculate?

Maths Magic 🔢 
ok but seriously
i took the number of characters I changed 
Took number of total character

and did some maths stuff(definitely not using calculator)

**Comment by ghost** [comment]
> > how did you calculate?
> 
> Maths Magic 🔢
> ok but seriously
> i took the number of characters I changed
> Took number of total character
> 
> and did some maths stuff(definitely not using calculator)

so you use a calculator...

**Pull request merged**
